<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Commands\Transaction\UpdateTransaction\**" />
    <EmbeddedResource Remove="Commands\Transaction\UpdateTransaction\**" />
    <None Remove="Commands\Transaction\UpdateTransaction\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TransactionService.Domain\TransactionService.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\Transaction\UpdateTransaction - Copier\" />
  </ItemGroup>

</Project>
